name: CoreProtectTNT
main: com.leir4iks.coreprotecttnt.Main
version: ${project.version}
api-version: 1.21
depend:
  - CoreProtect
authors: [GhostChu, leir4iks, ApliNi, danikovdev]
folia-supported: true
